### ISSUE TITLE
install.sh seems to installs wrong node version

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#804]
After installing in a fresh unix user home, I got the following error : 

```
gtest@vps55093:/opt/gtest$ duniter wizard config
/opt/gtest/.duniter/index.js:125
      }, (...args) => that.processCommand.apply(null, [command].concat(args)));
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/gtest/.duniter/bin/duniter:5:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by M5oul** [comment]
The [Node.js version number must be updated](https://github.com/duniter/duniter/blob/master/install.sh#L64) to version 6.9.4.

**Comment by M5oul** [comment]
So, now Duniter is only compatible with Node.js 6.x?
No more with version 4.x and 5.x?

**Comment by c-geek** [comment]
@M5oul yes, but I hadn't planned this. I just used ES6 syntax, and as my dev environment uses Node.js 6 (which is the official LTS version), I decided to bump Duniter to Node.js 6.

**Comment by M5oul** [comment]
Ok.

**Comment by c-geek** [comment]
@Insoleet you can retry, I've upgraded the Node.js version in `install.sh`.

**Comment by Insoleet** [comment]
Still broken : 

```
gtest@vps55093:/opt/gtest$ wget -qO- https://raw.githubusercontent.com/duniter/duniter/master/install.sh | bash
=> Downloading duniter from git to '/opt//gtest/.duniter'
=> Cloning into '/opt//gtest/.duniter'...
remote: Counting objects: 27834, done.
remote: Compressing objects: 100% (516/516), done.
remote: Total 27834 (delta 283), reused 0 (delta 0), pack-reused 27311
Receiving objects: 100% (27834/27834), 11.17 MiB | 6.68 MiB/s, done.
Resolving deltas: 100% (18751/18751), done.
Your version of git is out of date. Please update it!
=> Downloading 'http://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-x64.tar.gz' to '/opt//gtest/.duniter/node.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.2M  100 13.2M    0     0  7480k      0  0:00:01  0:00:01 --:--:-- 7641k
/usr/bin/env: node: No such file or directory

=> Appending source string to /opt//gtest/.bashrc
===> !Run the command 'source /opt//gtest/.bashrc' to start using duniter! <===
gtest@vps55093:/opt/gtest$ duniter config wizard
module.js:471
    throw err;
    ^

Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gtest/.duniter/bin/duniter:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by c-geek** [comment]
You can try again, should be fixed.

**Comment by c-geek** [comment]
May you close if it's fixed on your side @Insoleet?

**Comment by Insoleet** [comment]
I tried again but I'm not sure its fixed. I removed `.config/duniter` , `.duniter` , `.npm`, `.node-gpy`  but the installation seems to crash (See `bash: line 36: 14746 Killed   `)

```
testnet@vps55093:/opt/testnet$ curl -kL https://raw.githubusercontent.com/duniter/duniter/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5960  100  5960    0     0   172k      0 --:--:-- --:--:-- --:--:--  232k
=> Downloading duniter from git to '/opt/testnet//.duniter'
=> Cloning into '/opt/testnet//.duniter'...
remote: Counting objects: 27858, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 27858 (delta 5), reused 0 (delta 0), pack-reused 27834
Receiving objects: 100% (27858/27858), 11.06 MiB | 6.96 MiB/s, done.
Resolving deltas: 100% (18875/18875), done.
Your version of git is out of date. Please update it!
=> Downloading 'http://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-x64.tar.gz' to '/opt/testnet//.duniter/node.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.2M  100 13.2M    0     0  9344k      0  0:00:01  0:00:01 --:--:-- 9386k
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
bash: line 36: 14746 Killed                  $NODE $NPM installtEntry lib/config/config-validator.js

=> Appending source string to /opt/testnet//.bashrc
===> !Run the command 'source /opt/testnet//.bashrc' to start using duniter! <===
testnet@vps55093:/opt/testnet$ exit
exit
➜  ~ su testnet
testnet@vps55093:/root$ duniter
module.js:471
    throw err;
    ^

Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/testnet/.duniter/bin/duniter:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by c-geek** [comment]
Yes, you cannot do this under root mode.

**Comment by Insoleet** [comment]
I didn't do it as root (I exited and su to testnet back, that why root path appears, but install still failed).

**Comment by c-geek** [comment]
Can you please gimme Linux version, etc. I tested on fresh Ubuntu 16.04 and it is working, so maybe I need to test another distribution.

**Comment by Insoleet** [comment]
I'm using debian 7.

**Comment by Insoleet** [comment]
I tried again this morning and it worked as intended. Did you change anything in the installation process ?

**Comment by c-geek** [comment]
The last time I changed something on install.sh was on https://github.com/duniter/duniter/commit/95367d0f3dab40333648c9017e3bee11aafd1c87#diff-3fbb47e318cd8802bd325e7da9aaabe8

**Comment by M5oul** [comment]
Seems fixed. I close.
